import { Geist, Geist_Mono,Vollkorn } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";
import Header from "./component/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
 const vollkorn = Vollkorn({
  // variable: "--font-vollkorn",
  subsets: ["latin"],
});
export const metadata = {
  title: "Learn",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${vollkorn.className}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
